server:
  port: ${SPRING_SERVER_PORT}

spring:
  rabbitmq:
    port: ${RABBIT_MQ_PORT}
    host: ${RABBIT_HOST}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

app:
  rabbitmq:
    exchange:
      data: iot.data.exchange
      analytics: analytics.exchange
      alerts: alerts.exchange
