spring:
  main:
    banner-mode: console
  config:
    import:
      - optional:classpath:application-common.yml

app:
  rabbitmq:
    queue:
      rule-engine:
        name: iot-rule-engine.queue
        ttl: 5000
  rules:
    duration-rules:
      required-packets: 10
