spring:
  main:
    banner-mode: console
  config:
    import:
      - optional:classpath:application-common.yml
  data:
    mongodb:
      uri: ${MONGO_URI}

app:
  rabbitmq:
    queue:
      analytics:
        name: analytics.queue
      alerts:
        name: alerts.queue
  mongodb:
    collection:
      devices: devices
      analytics: analytics
      alerts: alerts
