global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'iot-controller'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['iot-controller:8080']

  - job_name: 'iot-analytics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['iot-analytics:8080']

  - job_name: 'iot-rule-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['iot-rule-engine:8080']
