spring:
  main:
    banner-mode: console
  config:
    import:
      - optional:classpath:application-common.yml

app:
  rabbitmq:
    queue:
      analytics:
        name: iot-analytics.queue
        ttl: 5000
  analytics:
    default-method: Sequential
    default-batch-size: 50
